In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/students_cleaned.csv")
df.shape

(2392, 14)

In [2]:
df_features = df.drop(columns=['GPA'])
df_features.columns.tolist()

['Age',
 'Gender',
 'Ethnicity',
 'ParentalEducation',
 'StudyTimeWeekly',
 'Absences',
 'Tutoring',
 'ParentalSupport',
 'Extracurricular',
 'Sports',
 'Music',
 'Volunteering',
 'GradeClass']

In [3]:
X = df_features.drop(columns=['GradeClass'])
y = df_features['GradeClass']

print(X.shape, y.shape)
X.columns.tolist()

(2392, 12) (2392,)

['Age',
 'Gender',
 'Ethnicity',
 'ParentalEducation',
 'StudyTimeWeekly',
 'Absences',
 'Tutoring',
 'ParentalSupport',
 'Extracurricular',
 'Sports',
 'Music',
 'Volunteering']

In [4]:
X = pd.get_dummies(X, columns=['Ethnicity'], prefix='Ethnicity')
X.columns.tolist()

['Age',
 'Gender',
 'ParentalEducation',
 'StudyTimeWeekly',
 'Absences',
 'Tutoring',
 'ParentalSupport',
 'Extracurricular',
 'Sports',
 'Music',
 'Volunteering',
 'Ethnicity_0',
 'Ethnicity_1',
 'Ethnicity_2',
 'Ethnicity_3']

In [5]:
X['HighAbsenceFlag'] = (df_features['Absences'] > 15).astype(int)
X[['Absences', 'HighAbsenceFlag']].head()

   Absences  HighAbsenceFlag
0         7                0
1         0                0
2        26                1
3        14                0
4        17                1

In [6]:
print("Final features:", X.columns.tolist())
print("Shape:", X.shape)
X.head()

Final features: ['Age', 'Gender', 'ParentalEducation', 'StudyTimeWeekly', 'Absences', 'Tutoring', 'ParentalSupport', 'Extracurricular', 'Sports', 'Music', 'Volunteering', 'Ethnicity_0', 'Ethnicity_1', 'Ethnicity_2', 'Ethnicity_3', 'HighAbsenceFlag']
Shape: (2392, 16)

,Age,Gender,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,Ethnicity_0,Ethnicity_1,Ethnicity_2,Ethnicity_3,HighAbsenceFlag
0,17,1,2,19.833723,7,1,2,0,0,1,0,True,False,False,False,0
1,18,0,1,15.408756,0,0,1,0,0,0,0,True,False,False,False,0
2,15,0,3,4.210570,26,0,2,0,0,0,0,False,False,True,False,1
3,17,1,3,10.028829,14,0,3,1,0,0,0,True,False,False,False,0
4,17,1,2,4.672495,17,1,3,0,0,0,0,True,False,False,False,1

In [8]:
import os
os.makedirs("../data/processed", exist_ok=True)
X.to_csv("../data/processed/X_features.csv", index=False)
y.to_csv("../data/processed/y_target.csv", index=False)